function json2table(t, o) {
  let i,
    e,
    n = t,
    r = document.getElementById(o);
  (document.getElementById("candidaturas").innerHTML =
    "Total Candidaturas: " + n.length);

    n.forEach((t) => {
      i = r.insertRow();
      for (const [o, n] of Object.entries(t)) {
        let t =
            "location=yes,height=570,width=520,scrollbars=yes,status=yes,top=-1000",
          r = n;
        if ("CM" === o && n.cv)
          (r = n.cv),
            (e = i.insertCell()),
            (a = document.createElement("a")),
            a.setAttribute("onClick", `window.open("${r}", "_blank", "${t}");`),
            a.setAttribute("title", "Abrir Biografia/CV"),
            (a.textContent = n.nome),
            e.appendChild(a),
            e.setAttribute("data-label", o);
        else if ("AM" == o && n.cv) {
            r = n.cv;
          (e = i.insertCell()),
            (a = document.createElement("a")),
            a.setAttribute("onClick", `window.open("${r}", "_blank", "${t}");`),
            a.setAttribute("title", "Abrir Biografia/CV"),
            (a.textContent = n.nome),
            e.appendChild(a),
            e.setAttribute("data-label", o);
        } else
          n && "Plataforma" === o
            ? ((e = i.insertCell()),
            (r = n),
            (a = document.createElement("a")),
            a.setAttribute("onClick", `window.open("${r}", "_blank", "${t}");`),
            a.setAttribute("title", "Ir para Plataforma"),
            (a.textContent = "Link"),
            e.appendChild(a),
            e.setAttribute("data-label", o))
            : n && "Contato" == o
            ? ((e = i.insertCell()),
              (a = document.createElement("a")),
              a.setAttribute("href", "mailto:" + n),
              (a.textContent = n),
              e.appendChild(a),
              e.setAttribute("data-label", o))
            : "PE" === o  && n
            ? ((e = i.insertCell()),
              (r = n),
              (a = document.createElement("a")),
              a.setAttribute("onClick", `window.open("${r}", "_blank", "${t}");`),
              a.setAttribute("title", "Abrir Programa Eleitoral"),
              (a.textContent = "Link"),
              e.appendChild(a),
              e.setAttribute("data-label", o))
              : "Lista" === o && n.cm
              ? ((e = i.insertCell()),
                (r = n),
                (a = document.createElement("a")),
                (i = document.createElement("span")),
                a.setAttribute("onClick", `window.open("${r.cm}", "_blank", "${t}");`),
                a.setAttribute("title", "Ver Listas"),
                // (a.textContent = ""),
                i.setAttribute("class","glyphicon glyphicon-list-alt"),
                e.appendChild(a),
                a.appendChild(i),
                e.setAttribute("data-label", o))
            : n
            ? ((e = i.insertCell()),
              (e.textContent = n),
              e.setAttribute("data-label", o))
            : (e = i.insertCell());
      }
    });
}
var tabela = [
  {
    Candidatura: "PAICV",
    CM: {nome:"Albertino Mosso",cv:"https://www.linkedin.com/in/albertino-mosso-14a352134/"},
    AM: "Manuel Portugal",
    Município: "Sal",
    Ilha: "Sal",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://facebook.com/AlbertinoMosso2020/",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_SAL.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: { nome: "Albertino Graça", cv: "http://www.albertinograca.cv/" },
    AM: {
      nome: "Leila de Pina",
      cv:
        "https://noticiasdonorte.publ.cv/104696/s-vicente-leila-barros-a-cabeca-de-lista-do-paicv-para-a-assembleia-municipal/",
    },
    Município: "São Vicente",
    Ilha: "São Vicente",
    Região: "Barlavento",
    PE: "",
    Plataforma: "",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_SAOVICENTE.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Alberto Nunes",cv:"https://docs.google.com/document/d/e/2PACX-1vQySxl5KKLke73BL6kWS85xIDQdmKRu4lIGQJe67c3rY9nec29-Pt3n_ca6lY3FDC8-q2CNwXJvVgu-/pub"},
    AM: "Luís Alves",
    Município: "Santa Catarina",
    Ilha: "Fogo",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://santacatarinafogo.mpd.cv/",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_SANTA_CATARINA_FOGO.pdf"},
  },
  {
    Candidatura: "SAL",
    CM: {nome:"Aldirley Gomes",cv:"https://inforpress.cv/autarquicas-2020-sal-biografia-de-aldirley-gomes-cabeca-de-lista-independente/"},
    AM: "Selizia Ribeiro",
    Município: "Sal",
    Ilha: "Sal",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://facebook.com/aldirleySal2020",
    Contato: "aldirley@salgrupoindependente.com",
    Lista: {cm:"https://drive.google.com/file/d/1Q4Parea9SkXesHiffdQpSfZHttPdYVco/view"},
  },
  {
    Candidatura: "PP",
    CM: "Amândio Vicente",
    AM: "Juvenal Furtado",
    Município: "Praia",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "https://facebook.com/Foradeface/posts/3337801602969948",
    Plataforma: "https://facebook.com/Foradeface",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PP_PRAIA.pdf"},
  },
  {
    Candidatura: "LSCP",
    CM: {nome:"Ana dos Reis",cv:"https://www.lscpraia.net/conhe%C3%A7a-anny-reis"},
    AM: {nome:"Amarílio dos Santos",cv:"https://www.lscpraia.net/c%C3%B3pia-conhe%C3%A7a-anny-reis"},
    Município: "Praia",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "https://www.lscpraia.net/c%C3%B3pia-plataforma",
    Plataforma: "https://www.lscpraia.net/",
    Contato: "lscpraia@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/LSCP_PRAIA.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Ângelo Vaz",cv:"https://docs.google.com/document/d/e/2PACX-1vShV6_RFUus4txgGmi004v9EWE8PNHgkon5-aTZnhh8LssZYt0tyI9ZK5swhz7HgezZm8VuBkQpWRn8/pub"},
    AM: "Elsa Rodrigues",
    Município: "São Salvador do Mundo",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "https://drive.google.com/file/d/1-11iM9oeKhUxnHQVAhkp-6MZZha1ivN_/view",
    Plataforma: "https://facebook.com/%C3%82ngelo-Vaz-Duca-2020-110581630780896",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_S%C3%83O-SALVADOR-DO-MUNDO.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"António Aleixo",cv:"https://inforpress.cv/autarquicas-2020-paul-biografia-de-antonio-aleixo-martins-cabeca-de-lista-do-mpd/"},
    AM: "Sandra Rodrigues",
    Município: "Paúl",
    Ilha: "Santo Antão",
    Região: "Barlavento",
    PE: "",
    Plataforma: "",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_PA%C3%9AL.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM:{nome: "António Fernandes",cv:"https://paicv.cv/autarquicas-2020-sao-lourenco-dos-orgaos-biografia-de-antonio-fernandes-cabeca-de-lista-do-paicv/"},
    AM: "Victor Baessa",
    Município: "São Lourenço dos Órgãos",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/presidentetone",
    Contato: "antoniofernandespaicv@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_S%C3%83O-LOUREN%C3%87O-DOS-%C3%93RG%C3%83OS.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: {nome:"António Ramos",cv:"http://paicv.cv/autarquicas-2020-maio-biografia-de-antonio-ramos-cabeca-de-lista-do-paicv/"},
    AM: "Michael Frederico",
    Município: "Maio",
    Ilha: "Maio",
    Região: "Sotavento",
    PE: "",
    Plataforma: "",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_MAIO.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Aníbal Fonseca",cv:"https://noticias.sapo.cv/actualidade/artigos/autarquicas-2020porto-novo-biografia-de-anibal-fonseca-cabeca-de-lista-mpd"},
    AM: "Jaqueline Rocha",
    Município: "Porto Novo",
    Ilha: "Santo Antão",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://portonovo.mpd.cv/",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_PORTO-NOVO.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: {nome:"Armindo Freitas",cv:"https://inforpress.cv/autarquicas-2020-santa-catarina-biografia-de-armindo-freitas-cabeca-de-lista-do-paicv/"},
    AM: "Ermelindo Fernandes",
    Município: "Santa Catarina",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://rb.gy/offkgj",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_SANTA-CATARINA-SANTIAGO.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Augusto Neves",cv:"https://www.cmsv.cv/index.php/municipio/camara-municipal/executivo/133-executivo/257-presidente-augusto-neves"},
    AM: {nome:"Lídia Lima", cv:"https://www.cmsv.cv/index.php/municipio/camara-municipal/executivo/133-executivo/286-vereadora-lidia-lima"},
    Município: "São Vicente",
    Ilha: "São Vicente",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://saovicente.mpd.cv/",
    Contato: "augustoneves2020marketing@gmail.com",
    Lista: {cm:"https://saovicente.mpd.cv/lista-cmsv/"},
  },
  {
    Candidatura: "GRIDT",
    CM: {nome:"Balduíno Rosário",cv:"https://inforpress.cv/autarquicas-2020-tarrafal-de-sao-nicolau-balduino-do-rosario-garante-que-tem-programa-ambicioso-no-desporto-para-o-municipio/"},
    AM: "Elton Sequeira",
    Município: "Tarrafal",
    Ilha: "São Nicolau",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://facebook.com/vivagridt",
    Contato: "sameilopes@yahoo.com.br",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/GRIDT_TARRAFAL_SN.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: {nome:"Carlos Barbosa",cv:"https://noticias.sapo.cv/actualidade/artigos/autarquicas-2020ribeira-brava-biografia-de-carlos-barbosa-candidato-do-paicv"},
    AM: "Antonino Brito",
    Município: "Ribeira Brava",
    Ilha: "São Nicolau",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://facebook.com/Kadabra2020",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_RIBEIRA_BRAVA_SN.pdf"},
  },{
    Candidatura: "LUTA",
    CM:"Carlos Manuel Tavares",
    AM: "Jónica Tavares",
    Município: "Praia",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/lutacv2020",
    Contato: "lutacv10@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/LUTA_PRAIA.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: {nome:"Carlos Silva",cv:"https://noticias.sapo.cv/actualidade/artigos/autarquicas-2020santa-cruz-biografia-de-carlos-silva-cabeca-de-lista-do-paicv"},
    AM: "Gilson Cardoso",
    Município: "Santa Cruz",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "https://drive.google.com/file/d/1Jo7D-91uZT-XVoaH56oL5-oMOKx-s9wC/view",
    Plataforma: "https://facebook.com/Sueck2020/",
    Contato: "sueksilva@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_SANTA-CRUZ.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: {
      nome: "Carlos Pires Ferreira",
      cv:
        "https://drive.google.com/file/d/0B-pIHm7n-O2ONHlfVlZlTFhmakk/view?usp=sharing",
    },
    AM: "Wanderleya Nascimento",
    Município: "Paúl",
    Ilha: "Santo Antão",
    Região: "Barlavento",
    PE: "https://facebook.com/carlospiresferreira2020/posts/198950721669568",
    Plataforma: "https://facebook.com/carlospiresferreira2020",
    Contato: "carlospiresferreira2020@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_PA%C3%9AL.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Carlos Vasconcelos",cv:"https://noticias.sapo.cv/actualidade/artigos/autarquicas-2020sao-lourenco-dos-orgaos-biografia-de-carlos-vasconcelos-cabeca-de-lista-do-mpd"},
    AM: "Emanuel Gonçalves",
    Município: "São Lourenço dos Órgãos",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/saolourecodosorgaosvamosseguiremfrente",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_S%C3%83O-LOUREN%C3%87O-DOS-%C3%93RG%C3%83OS-1.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {
      nome: "Celso Ribeiro",
      cv:
        "https://www.facebook.com/notes/celso-ribeiro-construindo-novo-tempo-novo-tarrafal/celso-ribeiro/121822176241886/",
    },
    AM: "Maria Rosa Semedo",
    Município: "Tarrafal",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_TARRAFAL-DE-SANTIAGO.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Clemente Garcia",cv:"https://docs.google.com/document/d/e/2PACX-1vTumqmw7Lv5IrXfWx_XUN7w_pHx6spb0URCKMA0is_WqVk-GxxV7D41uyAHmFChnpTvauObFfl0tBRX/pub"},
    AM: "Admilson Moniz",
    Município: "São Domingos",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://saodomingos.mpd.cv/",
    Contato: "clementegarcia1@hotmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_S%C3%83O-DOMINGOS.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: "Cláudio Mendonça",
    AM: "Walter Évora",
    Município: "Boa Vista",
    Ilha: "Boa Vista",
    Região: "Barlavento",
    PE: "https://www.flipsnack.com/Eldini/plataforma-eleitoral-da-candidatura-boavista-merece-mais.html",
    Plataforma: "https://facebook.com/BubistaMereceMais",
    Contato: "candidaturaclaudiomendonca@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_BOAVISTA.pdf"},
  },
  {
    Candidatura: "MIT",
    CM: "Cláudio Sousa",
    AM: "Adelino da Silva",
    Município: "Tarrafal",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/MIT-Movimento-Independente-Tarrafal-MITarrafal-111363727312283/?ref=page_internal",
    Contato: "mitarrafal@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MIT_TARRAFAL-DE-SANTIAGO.pdfs"},
  },
  {
    Candidatura: "PAICV",
    CM: "Clóvis Silva",
    AM: {nome:"Margarida Fernandes", cv:"https://docs.google.com/document/d/e/2PACX-1vSyXNK2G52ie9BB63ZWq7bvq_TT_9mgP0E4bcCyvoWsO4pZ7n8GmurIlB8tuMFOob8PKagznZOILlui/pub"},
    Município: "Brava",
    Ilha: "Brava",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/CL0VISILD0",
    Contato: "clovisildo@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_BRAVA.pdf"},
  },{
    Candidatura: "DSB",
    CM:{nome:"Denise Tavares",cv:"https://facebook.com/watch/?v=1435489803324574"},
    AM: "Miguel de Barros",
    Município: "Praia",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/DJA-STA-BOM-Praia-102423084912304",
    Contato: "596 66 96",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/DSB_PRAIA.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: "Domingos Mendes",
    AM: "António Monteiro",
    Município: "Ribeira Grande",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/DomingosCMRGS2020",
    Contato: "candidaturadomingos2020@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_RIBEIRA-GRANDE-SANTIAGO.pdf"},
  },
  {
    Candidatura: "UCID",
    CM: {nome:"Domingos Rodrigues",cv:"https://inforpress.cv/autarquicas-2020-porto-novo-candidato-da-ucid-considera-que-processo-de-desenvolvimento-do-municipio-tem-sido-lento/"},
    AM: "José Manuel Graça",
    Município: "Porto Novo",
    Ilha: "Santo Antão",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://web.facebook.com/Candidatura-Domingos-Rodrigues-UCID-100842595081369/",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/UCID_PORTO-NOVO.pdf"},
  },
  {
    Candidatura: "UT",
    CM: "Domingos Semedo",
    AM: "Luis de Pina",
    Município: "Tarrafal",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/EmilioTitaDomingos",
    Contato: "emiliotita.domingossemedo@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/UT_TARRAFAL-DE-SANTIAGO.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: "Eugénio Veiga",
    AM: "Irilandia Andrade",
    Município: "Santa Catarina",
    Ilha: "Fogo",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/eugenioveiga2020",
    Contato: "972 05 80",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_SANTA_CATARINA_FOGO.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: "Fábio Vieira",
    AM: "Lúcio Fernandes",
    Município: "Mosteiros ",
    Ilha: "Fogo",
    Região: "Sotavento",
    PE: "",
    Plataforma: "",
    Contato: "paicvmosteiros@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_MOSTEIROS.pdf"},
  },
  {
    Candidatura: "SAT",
    CM:{nome: "Felix Cardoso",cv:"https://inforpress.cv/autarquicas-2020-santa-catarina-biografia-de-felix-cardoso-cabeca-de-lista-de-candidatura-independente/"},
    AM: "Alcides da Moura",
    Município: "Santa Catarina ",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "https://drive.google.com/file/d/1bos8MsoXOCva6eYieONranIor57XFYM_/view?fbclid=IwAR3H1y6kZSea4v8-QejaL8ZYNpnqFdex-_PTjyL-jg3Cv_tPZIrNTyrEwYU",
    Plataforma: "https://cutt.ly/0gjFtcO",
    Contato: "",
    Lista: {cm:"https://drive.google.com/file/d/1jJfIFolnTe5xtinclFeEwWATl39-IgyY/view"},
  },
  {
    Candidatura: "PAICV",
    CM: "Francisco Carvalho",
    AM: "Maria Clara Marques",
    Município: "Praia",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://cutt.ly/XgjFXtj",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_PRAIA.pdf"},
  },
  {
    Candidatura: "UCID",
    CM: "Francisco Silva",
    AM: "Juceliano Vieira",
    Município: "Praia",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "https://www.flipsnack.com/stevenn1989/vis-o-estrat-gica-da-candidatura-ucid-na-praia.html",
    Plataforma: "https://facebook.com/UNIDOSPELAPRAIA2020/",
    Contato: "frangsilva@hotmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/UCID_PRAIA.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: "Francisco Tavares",
    AM: "Fernanda Burgo",
    Município: "Brava",
    Ilha: "Brava",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/franciscotavares2020",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_BRAVA.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: "Herménio Fernandes",
    AM: "Leocádia Furtado",
    Município: "São Miguel",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/SaoMiguelPraFrente",
    Contato: "candidatura.meno2016@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_S%C3%83O-MIGUEL-CALHETA.pdf"},
  },
  {
    Candidatura: "UCID",
    CM: "Holden Duarte",
    AM: "Rosa Lopes",
    Município: "Tarrafal",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/Holden-Duarte-Candidato-a-CMTS-2020-131457495319219/",
    Contato: "duarteholden@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/UCID_TARRAFAL-DE-SANTIAGO.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: "Isaías Varela",
    AM: "Felismina Moreno",
    Município: "São Domingos",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://www.isaiasvarela.online/",
    Contato: "isaiasamvarela2020@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_S%C3%83O-DOMINGOS.pdf"},
  },
  {
    Candidatura: "MJT",
    CM: "Jeremias Garcia",
    AM: "Danilson Monteiro",
    Município: "Praia",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/MJT2020CV",
    Contato: "movimentojusticatrabalho@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MJT_PRAIA.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: "Jorge Nogueira",
    AM: "Adolfo Rodrigues",
    Município: "São Filipe",
    Ilha: "Fogo",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://saofilipe.mpd.cv/",
    Contato: "jorgenogueiracv@gmail.com",
    Lista: {cm:"https://drive.google.com/file/d/1r3hSaf2ifG6eocXFukuYg4wi-J-oCK-m/view?usp=sharing"},
  },
  {
    Candidatura: "MPD",
    CM: "José Alves",
    AM: "Eurico da Moura",
    Município: "Santa Catarina",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/SomadaRibaLa/",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_SANTA-CATARINA-SANTIAGO.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: "José Brito",
    AM: "Raimundo Lopes",
    Município: "Tarrafal",
    Ilha: "São Nicolau",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://facebook.com/Z%C3%A9-dBia-Mana-Aut%C3%A1rquicas-2020-107254571058956",
    Contato: "jose.freitasbrito@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_TARRAFAL_SN.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: "José L. Santos",
    AM: "Elizabete Évora",
    Município: "Boa Vista",
    Ilha: "Boa Vista",
    Região: "Barlavento",
    PE: "https://drive.google.com/file/d/1L_Q5g-GE4zPifTdtAE-I0Ne89FGdx3Xy/view",
    Plataforma: "https://facebook.com/djaiss2020",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_BOAVISTA.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: "José Martins",
    AM: "Benvindo Almeida",
    Município: "Ribeira Brava",
    Ilha: "São Nicolau",
    Região: "Barlavento",
    PE: "https://facebook.com/zecamartins2020/posts/662881061060343",
    Plataforma: "https://facebook.com/zecamartins2020",
    Contato: "jozmartins7@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_RIBEIRA_BRAVA_SN.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: {nome:"José dos Reis Varela",cv:"https://inforpress.cv/autarquicas-2020-tarrafal-biografia-do-candidato-do-paicv-jose-dos-reis-varela/"},
    AM: "Adilson Costa",
    Município: "Tarrafal",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/mayka2020",
    Contato: "maykapresidente2020@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_TARRAFAL-DE-SANTIAGO.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: "João Alberto de Barros",
    AM: "Nasolino Gomes de Carvalho",
    Município: "São Salvador do Mundo",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_S%C3%83O-SALVADOR-DO-MUNDO.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: "João Carvalho",
    AM: "Carla Carvalho",
    Município: "São Miguel",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/Porsaomiguel",
    Contato: "joccarvalho2008@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_S%C3%83O-MIGUEL-CALHETA.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: "João Soares",
    AM: "Manuel Fernandes",
    Município: "Tarrafal",
    Ilha: "São Nicolau",
    Região: "Barlavento",
    PE: "",
    Plataforma: "",
    Contato: "",
    Lista: "",
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Júlio Lopes",cv:"https://inforpress.cv/autarquicas-2020-sal-biografia-de-julio-lopes-cabeca-de-lista-do-mpd/"},
    AM: "Nuno Santos",
    Município: "Sal",
    Ilha: "Sal",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://facebook.com/JulioLopesSal",
    Contato: "juliolopes.sal@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_SAL.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Lourenço Lopes",cv:"https://noticias.sapo.cv/actualidade/artigos/autarquicas-2020mosteiros-biografia-de-lourenco-lopes-cabeca-de-lista-do-mpd"},
    AM: "Francisco B. Amado",
    Município: "Mosteiros ",
    Ilha: "Fogo",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://mosteiros.mpd.cv/",
    Contato: "lourencolopesmosteiros@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_MOSTEIROS.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Miguel Rosa",cv:"https://noticias.sapo.cv/actualidade/artigos/autarquicas-2020maio-biografia-de-miguel-rosa-cabeca-de-lista-do-mpd"},
    AM: "Alcídia Maria Tavares",
    Município: "Maio",
    Ilha: "Maio",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/miguelrosa2016",
    Contato: "miguelrosa29@hotmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_MAIO.pdf"},
  },
  {
    Candidatura: "AMIESD",
    CM: {nome:"Milton Paiva",cv:"https://www.slideshare.net/slideshow/embed_code/key/5PaZNYvek6i2f3"},
    AM: "Ana Bela Teixeira",
    Município: "São Domingos",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/amiesandomingus/",
    Contato: "amiesandomingus@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/AMIESD_S%C3%83O-DOMINGOS.pdf"},
  },
  {
    Candidatura: "UCID",
    CM: "Neida Rompão",
    AM: "Adelgisa Monteiro",
    Município: "Santa Catarina",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/UCID_SANTA-CATARINA-SANTIAGO.pdf"},
  },
  {
    Candidatura: "MIMS",
    CM: {nome:"Nelson Lopes",cv:"https://massoncent.com/nelson-lopes/"},
    AM: "Albertino Gonçalves",
    Município: "São Vicente",
    Ilha: "São Vicente",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://massoncent.com/",
    Contato: "massoncent.gerais@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MIMS_SAOVICENTE.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: {nome:"Nelson Moreira",cv:"https://inforpress.cv/autarquicas-2020-ribeira-grande-de-santiago-biografia-de-nelson-vaz-moreira-cabeca-de-lista-do-paicv/"},
    AM: "José Gomes Veiga",
    Município: "Ribeira Grande",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/Nelson-nos-Prizidenti-RGS-101422328277889",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_RIBEIRA-GRANDE-SANTIAGO.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: {nome:"Nilton Dias",cv:"https://inforpress.cv/autarquicas-2020-porto-novo-biografia-de-nilton-dias-cabeca-de-lista-do-paicv/"},
    AM: "Vitória Sabino",
    Município: "Porto Novo",
    Ilha: "Santo Antão",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://facebook.com/niltoncmpn",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_PORTO-NOVO.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: {
      nome: "Nuías Silva",
      cv: "https://cv.linkedin.com/in/nuias-mendes-barbosa-da-silva-96a16629",
    },
    AM: "Luís Nunes",
    Município: "São Filipe",
    Ilha: "Fogo",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/nuiasmbsilva2020",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_SAOFILIPE_FOGO.pdf"},
  },
  {
    Candidatura: "PAICV",
    CM: {nome:"Odailson Bandeira",cv:"https://noticias.sapo.cv/actualidade/artigos/autarquicas-2020ribeira-grande-biografia-de-odailson-bandeira-cabeca-de-lista-do-paicv"},
    AM: "Armindo Cruz",
    Município: "Ribeira Grande",
    Ilha: "Santo Antão",
    Região: "Barlavento",
    PE: "",
    Plataforma: "",
    Contato: "elevarribeiragrande@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PAICV_RIBEIRA-GRANDE-SANTO-ANT%C3%83O.pdf"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Óscar Santos",cv:"https://docs.google.com/document/d/e/2PACX-1vT7PA2sNxuslQ-AQe0_blc0eQa5kJwKqf3lW6xT48Dd7A-Ut5OzVQvBELocEBf3Q0M1hTMgbdNd6oOH/pub"},
    AM: "Ana Barber",
    Município: "Praia",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://praia.mpd.cv/",
    Contato: "",
    Lista: {cm:"https://praia.mpd.cv/lista-cmp/", am:"https://praia.mpd.cv/lista-amp/"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Orlando Delgado",cv:"https://inforpress.cv/autarquicas-2020-ribeira-grande-biografia-de-orlando-delgado-cabeca-de-lista-do-mpd/"},
    AM: "Leida Maurício Andrade",
    Município: "Ribeira Grande",
    Ilha: "Santo Antão",
    Região: "Sotavento",
    PE: "",
    Plataforma: "https://facebook.com/Mpd-Ribeira-Grande-Santo-Ant%C3%A3o-535351126572909/",
    Contato: "mpdribeiragrandesa@gmail.com",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_RIBEIRA-GRANDE-SANTO-ANT%C3%83O.pdf"},
  },
  {
    Candidatura: "ARG",
    CM: {
      nome: "Paulino Dias",
      cv:
        "https://alternativaribeiragrande.cv/wp-content/uploads/2020/07/Curriculo-Paulino-Dias.pdf",
    },
    AM: {
      nome: "Licinia Leite",
      cv:
        "https://alternativaribeiragrande.cv/wp-content/uploads/2020/06/Curriculo-Licinia-Leite.pdf",
    },
    Município: "Ribeira Grande",
    Ilha: "Santo Antão",
    Região: "Barlavento",
    PE: "https://alternativaribeiragrande.cv/?page_id=462",
    Plataforma: "https://alternativaribeiragrande.cv/",
    Contato: "samlemos2015@gmail.com",
    Lista: {cm:"https://drive.google.com/file/d/1DvWbr_5gsTlYiOhC2SvfZOjnH54Gzxhl/view?usp=sharing"},
  },
  {
    Candidatura: "MPD",
    CM: {nome:"Pedro Rocha",cv:"https://noticias.sapo.cv/actualidade/artigos/autarquicas-2020santa-cruz-biografia-de-pedro-alexandre-rocha-cabeca-de-lista-do-mpd"},
    AM: "Orlando Dias",
    Município: "Santa Cruz",
    Ilha: "Santiago",
    Região: "Sotavento",
    PE: "",
    Plataforma: "",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/MPD_SANTA-CRUZ.pdf"},
  },
  {
    Candidatura: "UCID",
    CM: {nome:"Pedro Ribeiro",cv:"https://docs.google.com/document/d/e/2PACX-1vRP68ymT9Zg6RvNH8RDB0VdHMzhqk8MmamE5MKyT2ywBsvOsJptWFHYcf7C78sg9Krfy2wld4wvxbTT/pub"},
    AM: "Felizardo Afonso",
    Município: "São Filipe",
    Ilha: "Fogo",
    Região: "Sotavento",
    PE: "",
    Plataforma: "",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/UCID_SAOFILIPE_FOGO.pdf"},
},{
  Candidatura: "UCID",
    CM: {
      nome: "Sandro Lopes",
      cv:
        "https://inforpress.cv/autarquicas-2020-paul-biografia-de-sandro-gomes-cabeca-de-lista-da-ucid/",
    },
    AM: "Jailson Brito",
    Município: "Paúl",
    Ilha: "Santo Antão",
    Região: "Barlavento",
    PE: "",
    Plataforma: "https://facebook.com/CandidaturaSandroGomes",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/UCID_PA%C3%9AL.pdf"},
  },
  {
    Candidatura: "PP",
    CM: "",
    AM: {nome:"Sérgio Corrá",cv:"https://santiagomagazine.cv/index.php/politica/5063-sergio-corra-encabeca-lista-do-partido-popular-para-assembleia-municipal-da-boa-vista"},
    Município: "Boa Vista",
    Ilha: "Boa Vista",
    Região: "Barlavento",
    PE: "",
    Plataforma: "",
    Contato: "",
    Lista: {cm:"https://cne.cv/wp-content/uploads/2019/10/PP_BOAVISTA.pdf"},
  }
];
json2table(tabela, "ttbody");
